{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "my-nginx.fullname" . }}
  labels:
    {{- include "my-nginx.labels" . | nindent 4 }}
spec:
  path: {{ .Values.route.path | quote }}
  to:
    kind: Service
    name: {{ include "my-nginx.fullname" . }}
{{- end }}